log:
  disable_sentry: true
  level: debug

db:
  url: "postgres://tss:tss@localhost:5432/tss?sslmode=disable"

listener:
  addr: :9000

core:
  addr: tcp://localhost:26657

cosmos:
  addr: localhost:9090

session:
  start_block: 500
  start_session_id: 1

swagger:
  addr: :1313
  enabled: true

chain:
  chain_id: ""
  coin_name: ""