// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: controllers.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControllerType int32

const (
	ControllerType_CONTROLLER_KEYGEN     ControllerType = 0
	ControllerType_CONTROLLER_PROPOSAL   ControllerType = 1
	ControllerType_CONTROLLER_RESHARE    ControllerType = 2
	ControllerType_CONTROLLER_ACCEPTANCE ControllerType = 3
	ControllerType_CONTROLLER_SIGN       ControllerType = 5
	ControllerType_CONTROLLER_FINISH     ControllerType = 6
)

// Enum value maps for ControllerType.
var (
	ControllerType_name = map[int32]string{
		0: "CONTROLLER_KEYGEN",
		1: "CONTROLLER_PROPOSAL",
		2: "CONTROLLER_RESHARE",
		3: "CONTROLLER_ACCEPTANCE",
		5: "CONTROLLER_SIGN",
		6: "CONTROLLER_FINISH",
	}
	ControllerType_value = map[string]int32{
		"CONTROLLER_KEYGEN":     0,
		"CONTROLLER_PROPOSAL":   1,
		"CONTROLLER_RESHARE":    2,
		"CONTROLLER_ACCEPTANCE": 3,
		"CONTROLLER_SIGN":       5,
		"CONTROLLER_FINISH":     6,
	}
)

func (x ControllerType) Enum() *ControllerType {
	p := new(ControllerType)
	*p = x
	return p
}

func (x ControllerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControllerType) Descriptor() protoreflect.EnumDescriptor {
	return file_controllers_proto_enumTypes[0].Descriptor()
}

func (ControllerType) Type() protoreflect.EnumType {
	return &file_controllers_proto_enumTypes[0]
}

func (x ControllerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControllerType.Descriptor instead.
func (ControllerType) EnumDescriptor() ([]byte, []int) {
	return file_controllers_proto_rawDescGZIP(), []int{0}
}

var File_controllers_proto protoreflect.FileDescriptor

var file_controllers_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x9f,
	0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x52, 0x5f,
	0x4b, 0x45, 0x59, 0x47, 0x45, 0x4e, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x4f, 0x4e, 0x54,
	0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x52, 0x5f, 0x50, 0x52, 0x4f, 0x50, 0x4f, 0x53, 0x41, 0x4c, 0x10,
	0x01, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x52, 0x5f,
	0x52, 0x45, 0x53, 0x48, 0x41, 0x52, 0x45, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4e,
	0x54, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x52, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x41, 0x4e,
	0x43, 0x45, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x4c,
	0x45, 0x52, 0x5f, 0x53, 0x49, 0x47, 0x4e, 0x10, 0x05, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4e,
	0x54, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x52, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x10, 0x06,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x61, 0x72, 0x69, 0x6d, 0x6f, 0x2f, 0x74, 0x73, 0x73, 0x2f, 0x74, 0x73, 0x73, 0x2d, 0x73, 0x76,
	0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_controllers_proto_rawDescOnce sync.Once
	file_controllers_proto_rawDescData = file_controllers_proto_rawDesc
)

func file_controllers_proto_rawDescGZIP() []byte {
	file_controllers_proto_rawDescOnce.Do(func() {
		file_controllers_proto_rawDescData = protoimpl.X.CompressGZIP(file_controllers_proto_rawDescData)
	})
	return file_controllers_proto_rawDescData
}

var file_controllers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controllers_proto_goTypes = []interface{}{
	(ControllerType)(0), // 0: ControllerType
}
var file_controllers_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_controllers_proto_init() }
func file_controllers_proto_init() {
	if File_controllers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controllers_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controllers_proto_goTypes,
		DependencyIndexes: file_controllers_proto_depIdxs,
		EnumInfos:         file_controllers_proto_enumTypes,
	}.Build()
	File_controllers_proto = out.File
	file_controllers_proto_rawDesc = nil
	file_controllers_proto_goTypes = nil
	file_controllers_proto_depIdxs = nil
}
